name: Alliser - Check file types

on: [pull_request]

jobs:
  alliser:
    runs-on: ubuntu-latest
    name: Run Alliser
    steps:
    - name: Alliser action step
      uses: stscoundrel/alliser-action@v0.5.1
      with:
        extensions: ".ts"
        folders: "src,tests"
