name: Alliser - Check file types

on: [pull_request]

jobs:
  alliser:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Run Alliser with Node.js ${{ matrix.node-version }}
      uses: stscoundrel/alliser-action@v0.5.0
      with:
        extensions: .ts
        folders: src,tests
